// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TDP.BLL;

#nullable disable

namespace TDP.BLL.Migrations
{
    [DbContext(typeof(TdpDbContext))]
    partial class TdpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TDP.BLL.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("IDGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IDGuid = new Guid("f7a9e8b0-3c1d-4a9f-8b2a-1e6c9d7f8a3b"),
                            NameAR = "الموارد البشرية",
                            NameEN = "Human Resources"
                        },
                        new
                        {
                            ID = 2,
                            IDGuid = new Guid("a3b8d4c1-9e7f-4b0d-9c3a-2e8d7f6a5b4c"),
                            NameAR = "تقنية المعلومات",
                            NameEN = "Information Technology"
                        },
                        new
                        {
                            ID = 3,
                            IDGuid = new Guid("c9d8e7f6-5a4b-4c3d-8b2a-1e6d9c7f8a3b"),
                            NameAR = "المالية",
                            NameEN = "Finance"
                        });
                });

            modelBuilder.Entity("TDP.BLL.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IDGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = 2,
                            Email = "john.doe@example.com",
                            HashedPassword = "hashed_password_placeholder_1",
                            IDGuid = new Guid("d1e2f3a4-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            IsActive = true,
                            Name = "John Doe"
                        },
                        new
                        {
                            ID = 2,
                            BirthDate = new DateTime(1988, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = 1,
                            Email = "jane.smith@example.com",
                            HashedPassword = "hashed_password_placeholder_2",
                            IDGuid = new Guid("f5a4e3d2-c1b0-4a9f-8e7d-6c5b4a3f2e1d"),
                            IsActive = true,
                            Name = "Jane Smith"
                        },
                        new
                        {
                            ID = 3,
                            BirthDate = new DateTime(1992, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = 2,
                            Email = "peter.jones@example.com",
                            HashedPassword = "hashed_password_placeholder_3",
                            IDGuid = new Guid("a9b8c7d6-e5f4-4a3b-8c2d-1e9f8a7b6c5d"),
                            IsActive = false,
                            Name = "Peter Jones"
                        },
                        new
                        {
                            ID = 4,
                            BirthDate = new DateTime(1995, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = 3,
                            Email = "sara.miller@example.com",
                            HashedPassword = "hashed_password_placeholder_4",
                            IDGuid = new Guid("b3c2d1e0-f9a8-4e7d-6c5b-4a3f2e1d0c9b"),
                            IsActive = true,
                            Name = "Sara Miller"
                        });
                });

            modelBuilder.Entity("TDP.BLL.Models.Employee", b =>
                {
                    b.HasOne("TDP.BLL.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
